### ISSUE TITLE
serial port config op ubunty geeft foutmelding

### ISSUE THREAD

**Issue by hkiela** [jackha/sandbox#17]
De serial port dialoog geeft een foutmelding line 252 type error can't use a string pattern on a byte like object

of zoiets

**Comment by jackha** [comment]
onderzocht. waarschijnlijk omdat pyserial te oud is (2.6). Ik had het ook op een vers geinstalleerde pi.

upgraden met: 

pip3.2 install --upgrade pyserial

ook in readme verwerkt.
