### ISSUE TITLE
Eerste tests werken met de wielmodule

### ISSUE THREAD

**Issue by hkiela** [jackha/sandbox#4]
Dag Jack,
Je GUI werkt met de wielmodule. Ik kan verbinden en met de sliders het wiel en stuur bedienen.

Een paar kleine opmerkingen tav het hoofdscherm:
- het logscherm kan wel wat kleiner
- een knop toevoegen bij het logscherm om de data te loggen in een file
- een knop om de log file te openen
- De speed en steer actuele waarden en teruggelezen waarden bij elkaar in een frame zodat de verticale slider niet meer beweegt.
- De commando regel is wel handig, maar daar moet een label bij met iets als command.

**Comment by jackha** [comment]
de log knoppen heb ik niet, maar dingen worden wel in een directory gelogd. de rest zit erin.

**Comment by hkiela** [comment]
Ha Jack,
Ja je was lekker bezig.
Ik zag vanuit mijn ooghoeken dat de WIP versies terug naar de master zijn.

Heb je ook al de ingangs socket toegevoegd of staat die nog open

Ik ga morgen testen.

Groet
henk

jack schreef op 29-10-2015 om 18:42:
