### ISSUE TITLE
Het Edit/Debug scherm

### ISSUE THREAD

**Issue by hkiela** [jackha/sandbox#5]
Hier lijkt nog niets te werken.
Zoals gisteren besproken moet je alle commando's die regelmatig data opvragen in een  thread van het hoofdscherm zetten.

Zoals je in onderstaande pascal code ziet, wordt de eerste keer een $60, $29, $9 en $50 gegeven
daarna om de 100 ms $59, $58, $10, $13, $11.

    if (Timer2Count mod 10 = 0) then begin
      if firstcycle then begin  // Do these tasks only once after port is enabled
          SendPM(' $60'  + CR); // get adc labels
          SendPM(' $29'  + CR); // get afirmware
          SendPM(' $9'   + CR); // Reset min max values adc
          SendPM(' $50'  + CR); // Get PID parameters
        firstcycle:=false;      // reset this flag until next serialport enable
      end; // if firstcycle

      if automaticcommands then begin
        //if ((Timer2Count mod 3) = 0) then begin
          SendPM(' $59'  + CR);  // get counters
          SendPM(' $58'  + CR);  // get process times
          SendPM(' $10'  + CR);  // get voltages
          SendPM(' $13'  + CR);  // get actual speed and direction
          SendPM(' $11'  + CR);  // get status and errors

        //end; // if timer2 mod

**Comment by jackha** [comment]
done. alleen $50 deed ik eerst continue, nu alleen na $51 zodat de gui ook updated wordt.
